# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := xdp_limit_prog_kern

LIBBPF_DIR = ../xdp-tutorial/libbpf/src/
COMMON_DIR = ../xdp-tutorial/common

EXTRA_DEPS := $(COMMON_DIR)/parsing_helpers.h

include $(COMMON_DIR)/common.mk
